# Generated by Django 6.0 on 2026-02-13 00:18

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_id_store_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.store_logo_upload_to),
        ),
    ]
