# Generated by Django 6.0 on 2026-02-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='productimportbatch',
            old_name='id',
            new_name='uuid',
        ),
    ]
