# Generated by Django 6.0 on 2026-02-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_id_product_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tryon_template_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
