# Generated by Django 6.0 on 2026-03-14 13:47

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_tryon_template_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.product_image_upload_to),
        ),
    ]
