# Generated by Django 6.0 on 2026-03-14 15:20

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_uploaded_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tryon_asset",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=product.models.product_tryon_asset_upload_to,
            ),
        ),
    ]
