# Generated by Django 6.0.4 on 2026-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopping_preference',
            field=models.CharField(choices=[('menswear', 'Menswear'), ('womenswear', 'Womenswear'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
    ]
