# Generated by Django 6.0 on 2026-02-17 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_rename_id_product_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('image_url_used', models.URLField(max_length=2048)),
                ('product_url', models.URLField(blank=True, default='', max_length=2048)),
                ('store_name', models.CharField(blank=True, default='', max_length=255)),
                ('store_slug', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outfit.outfit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outfit_items', to='product.product')),
            ],
            options={
                'ordering': ['slot'],
                'constraints': [models.UniqueConstraint(fields=('outfit', 'slot'), name='unique_outfit_slot')],
            },
        ),
    ]
