# Generated by Django 6.0 on 2026-02-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='hidden_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
