# Generated by Django 6.0 on 2026-03-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0004_outfitlike_outfitsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='occasion',
            field=models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Smart Casual', 'Smart Casual'), ('Formal', 'Formal'), ('Wedding', 'Wedding'), ('Party', 'Party'), ('Birthday', 'Birthday'), ('Date Night', 'Date Night'), ('Work', 'Work'), ('Festival', 'Festival'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
