"""
Django settings for loud_fits_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import logging
import os
from pathlib import Path

from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = os.path.join(BASE_DIR, 'static')
logger = logging.getLogger(__name__)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(",")

ENABLE_GOOGLE_AUTH = config('ENABLE_GOOGLE_AUTH', default=False, cast=bool)
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default="", cast=str)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'user',
    'api',
    'authentication',
    'user_profile',
    'store',
    'product',
    'outfit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'loud_fits_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loud_fits_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = 'static/'
STATICFILES_DIRS = [STATIC_DIR]
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}

AWS_S3_ENABLED = config('AWS_S3_ENABLED', default=False, cast=bool)

if AWS_S3_ENABLED:
    required_aws_settings = {
        'AWS_ACCESS_KEY_ID': config('AWS_ACCESS_KEY_ID', default='', cast=str).strip(),
        'AWS_SECRET_ACCESS_KEY': config('AWS_SECRET_ACCESS_KEY', default='', cast=str).strip(),
        'AWS_REGION': config('AWS_REGION', default='', cast=str).strip(),
        'AWS_S3_MEDIA_BUCKET_NAME': config('AWS_S3_MEDIA_BUCKET_NAME', default='', cast=str).strip(),
    }
    missing_aws_settings = [
        setting_name
        for setting_name, setting_value in required_aws_settings.items()
        if not setting_value
    ]

    if missing_aws_settings:
        missing_message = (
            'AWS_S3_ENABLED=true but missing required AWS settings: '
            f'{", ".join(missing_aws_settings)}'
        )
        if DEBUG:
            logger.warning('%s. Falling back to local media storage.', missing_message)
        else:
            raise ImproperlyConfigured(missing_message)
    else:
        AWS_ACCESS_KEY_ID = required_aws_settings['AWS_ACCESS_KEY_ID']
        AWS_SECRET_ACCESS_KEY = required_aws_settings['AWS_SECRET_ACCESS_KEY']
        AWS_S3_REGION_NAME = required_aws_settings['AWS_REGION']
        AWS_STORAGE_BUCKET_NAME = required_aws_settings['AWS_S3_MEDIA_BUCKET_NAME']
        AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default='', cast=str).strip()

        aws_s3_endpoint_url = config('AWS_S3_ENDPOINT_URL', default='', cast=str).strip()
        AWS_S3_ENDPOINT_URL = aws_s3_endpoint_url or None

        AWS_DEFAULT_ACL = None
        AWS_QUERYSTRING_AUTH = True
        AWS_QUERYSTRING_EXPIRE = config(
            'AWS_QUERYSTRING_EXPIRE',
            default=3600,
            cast=int,
        )
        AWS_S3_OBJECT_PARAMETERS = {'ServerSideEncryption': 'AES256'}

        STORAGES['default'] = {
            'BACKEND': 'loud_fits_api.storage_backends.PrivateMediaStorage'
        }

        if AWS_S3_CUSTOM_DOMAIN:
            media_domain = AWS_S3_CUSTOM_DOMAIN.rstrip('/')
            if not media_domain.startswith(('http://', 'https://')):
                media_domain = f'https://{media_domain}'
            MEDIA_URL = f'{media_domain}/media/public/'
        elif AWS_S3_REGION_NAME == 'us-east-1':
            MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/public/'
        else:
            MEDIA_URL = (
                f'https://{AWS_STORAGE_BUCKET_NAME}.s3.'
                f'{AWS_S3_REGION_NAME}.amazonaws.com/media/public/'
            )

# CSRF settings
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS").split(",")

# CORS settings
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS").split(",")

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.User'

# Rest Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "uuid",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",
}
