# Generated by Django 6.0 on 2026-02-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='stylist_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
