# Generated by Django 6.0 on 2026-02-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_profile_role_profile_stylist_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='shopping_preference',
            field=models.CharField(blank=True, choices=[('MENSWEAR', 'Menswear'), ('WOMENSWEAR', 'Womenswear'), ('UNISEX', 'Unisex'), ('NO_PREFERENCE', 'No Preference')], max_length=15, null=True),
        ),
    ]
