# Generated by Django 6.0 on 2026-02-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_profile_gender_profile_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopping_preference',
            field=models.CharField(blank=True, choices=[('Menswear', 'Menswear'), ('Womenswear', 'Womenswear'), ('Unisex', 'Unisex'), ('No Preference', 'No Preference')], max_length=15, null=True),
        ),
    ]
